# Generated by Django 3.0.7 on 2021-03-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
