# Generated by Django 3.0.7 on 2021-03-27 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='pyment',
            new_name='payment',
        ),
    ]
