# Generated by Django 3.0.7 on 2021-03-27 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210327_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='zipe_code',
            new_name='zip_code',
        ),
    ]
